CC=gcc
CFLAGS=

n1: clean
	$(CC) $(CFLAGS) n1.c -o lab
n2: clean
	$(CC) $(CFLAGS) n2n.c -o lab
n4: clean
	$(CC) $(CFLAGS) n4.c -o lab
n6: clean
	$(CC) $(CFLAGS) n6.c -o lab
n7: clean
	$(CC) $(CFLAGS) n7.c -o lab
n8: clean
	$(CC) $(CFLAGS) n8.c -o lab
n10: clean
	$(CC) $(CFLAGS) n10.c -o lab
n11: clean
	$(CC) $(CFLAGS) n11.c -o lab
clean:
	rm -f lab a.out file
