CC=gcc
CFLAGS=

n1: clean
	$(CC) $(CFLAGS) n1.c -o lab
n2: clean
	$(CC) $(CFLAGS) n2.c -o lab
n3: clean
	$(CC) $(CFLAGS) n3.c -o lab
n4: clean
	$(CC) $(CFLAGS) n4.c -o lab
n5: clean
	$(CC) $(CFLAGS) n5.c -o lab
n6: clean
	$(CC) $(CFLAGS) n6.c -o n7.o
n7: clean
	$(CC) $(CFLAGS) n7.c -o n7.o
n8: clean
	$(CC) $(CFLAGS) n8.c -o n8.o
n9: clean
	$(CC) $(CFLAGS) n9.c -o n9.o
n10: clean
	$(CC) $(CFLAGS) n10.c -o n10.o
n11: clean
	$(CC) $(CFLAGS) n11.c -o n11.o

clean:
	rm -f *.o lab* a.out file slp prog matrix
